variable "external_id" {
  description = "Unique External ID generated by Resonant (found in your Resonant dashboard)"
  type        = string
  sensitive   = true

  validation {
    condition     = can(regex("^[a-zA-Z0-9-_]{16,64}$", var.external_id))
    error_message = "External ID must be 16-64 characters (alphanumeric, hyphens, underscores)"
  }
}

variable "resonant_aws_account_id" {
  description = "Resonant's AWS Account ID (provided by Resonant)"
  type        = string
  default     = "123456789012"  # Placeholder - will be replaced with actual Resonant account

  validation {
    condition     = can(regex("^\\d{12}$", var.resonant_aws_account_id))
    error_message = "Must be a valid 12-digit AWS Account ID"
  }
}

variable "role_name" {
  description = "Name for the IAM role"
  type        = string
  default     = "ResonantReadOnlyRole"

  validation {
    condition     = can(regex("^[a-zA-Z0-9+=,.@_-]{1,64}$", var.role_name))
    error_message = "Role name must be 1-64 characters and contain only valid IAM characters"
  }
}

variable "stage" {
  description = "Environment for the application (dev, stg, prd)"
  type        = string

  validation {
    condition = contains(["dev", "stg", "prd"], var.stage)
    error_message = "Invalid stage. Please choose 1 of: dev, stg, prd"
  }
}

variable "include_lambda" {
  description = "Include Lambda function scanning permissions"
  type        = bool
  default     = true
}

variable "include_ecs" {
  description = "Include ECS/Fargate scanning permissions"
  type        = bool
  default     = true
}