spring:
  application:
    name: resonant

  datasource:
    url: jdbc:postgresql://localhost:5432/resonant
    username: resonant_user
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # Flyway handles schema, so just validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

  # Security
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin}  # Temporary for development

# Server Configuration
server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-change-this-in-production-minimum-256-bits}
  expiration: 86400000  # 24 hours in milliseconds

#aws:
#  account-id: ${AWS_ACCOUNT_ID:}
#  region: ${AWS_REGION:us-east-1}

logging:
  level:
    root: INFO
    com.wenroe.resonant: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics